---
title: "Section 3.4.3 - Acoustic Fire Extinguisher"
author: "Marouane IL IDRISSI"
date: "03/12/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.path="figures/")

#Packages import
library(RColorBrewer)
library(lattice)
library(latticeExtra)
```

```{r}
#####################
# Setup

# Loading allocation results
load(file="results/allocations_AFE.RData")
load(file="../../useCases/acousticFireExtinguisher/data/AFE_data.RData")

# Plotting colors
coul <- brewer.pal(6, "Dark2") 
coul[3]="cornflowerblue"

AFE.names=colnames(fire[,-7])
```

# Acoustic Fire Extinguisher NN Model

```{r AFE_allocs,fig.width=10, fig.height=5.5}
par(mar=c(5,4.5,1,1),
    mfrow=c(1,2))


a=barplot(height=c(Shap.AFE$Shap)+0.005,
        names=AFE.names,
        col=coul,
        ylim=c(0,0.3),
        ylab="Shapley Effects",
        cex.names=1,
        cex.lab=1,
        xaxt="n",
        border=F)
 text(a, par("usr")[3], labels = AFE.names , srt = 60, adj = c(1.1,1.1), xpd = TRUE, cex=1) 
 perc<-paste(round(Shap.AFE$Shap*100, 2), "%", sep="")
 text(a, par("usr")[3]+.5, y=(Shap.AFE$Shap+0.02), labels = perc, xpd = TRUE, cex=0.9)
 
 
a=barplot(height=c(PME.AFE$PME)+0.005,
        names=AFE.names,
        col=coul,
        ylim=c(0,0.3),
        ylab="PME",
        cex.names=1,
        cex.lab=1,
        xaxt="n",
        border=F)
 text(a, par("usr")[3], labels = AFE.names , srt = 60, adj = c(1.1,1.1), xpd = TRUE, cex=1) 
 perc<-paste(round(PME.AFE$PME*100, 2), "%", sep="")
 text(a, par("usr")[3]+.5, y=(PME.AFE$PME+0.02), labels = perc, xpd = TRUE, cex=0.9)
```